smp/urls.py
from django.contrib import admin
from django.urls import path

from smpapp.views import (
    LPView,
    # teacher
    TeacherStartView,
    TeacherView,
    TeacherProfieView,
    StudentSearchView,
    StudentGradesFormView,
    FinalGradesFormView,
    PresenceListFormView,
    UnpreparedListFormView,
    # student
    StudentView,
    # auth
    LoginView,
    LogoutView,
    ChangePassView,
    signup,
    UserListView,
    # liblary
    LibraryView,
    NewBookFormView,
    BookUpdateView,
    BookDeleteView,
    BookDetailView,
    # auditorium
    RoomsView,

)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LPView.as_view(), name='lp'),

    # teacher
    path('teacher', TeacherStartView.as_view(), name='teacher_start'),
    path('teacher/<int:pk>', TeacherProfieView.as_view(), name='teacher_profile'),
    path('teacher/search', StudentSearchView.as_view(), name='teacher_search'),
    path('teacher/<int:class_id>/<int:subject_id>', TeacherView.as_view(), name='teacher_class'),
    path('teacher/<int:class_id>/<int:subject_id>/<int:student_id>/grades', StudentGradesFormView.as_view(), name='teacher_edit_grades'),
    path('teacher/<int:class_id>/<int:subject_id>/<int:student_id>/unpr', UnpreparedListFormView.as_view(), name='teacher_edit_unpr'),
    path('teacher/<int:class_id>/<int:subject_id>/<int:student_id>/pres', PresenceListFormView.as_view(), name='teacher_edit_pres'),
    path('teacher/<int:class_id>/<int:subject_id>/<int:student_id>/finalgrades', FinalGradesFormView.as_view(), name='teacher_final_grades'),
    # student
    path('student/<int:student_id>', StudentView.as_view(), name='student_view'),

    # auth
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('password_reset/<int:user_id>', ChangePassView.as_view(), name='password_reset'),
    path('signup', signup, name='signup'),
    path('list_users', UserListView.as_view(), name="list_users"),


    # liblary
    path('library', LibraryView.as_view(), name='library'),
    path('book_create', NewBookFormView.as_view(), name='book_create'),
    path('book_update/<int:pk>', BookUpdateView.as_view(), name='book_update'),
    path('book_delete/<int:pk>', BookDeleteView.as_view(), name='book_delete'),
    path('book_detail/<int:pk>', BookDetailView.as_view(), name='book_detail'),

    # auditorium
    #path('rooms', RoomsView.as_view(), name='rooms'),
]

smpapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.



''' ------------------- SCHOOL SECTION ------------------- '''

SCHOOL_CLASS = (
    (1, "1 klasa"),
    (2, "2 klasa"),
    (3, "3 klasa"),
)

GRADES = (
    (1, "1"),
    (1.5, "1+"),
    (1.75, "2-"),
    (2, "2"),
    (2.5, "2+"),
    (2.75, "3-"),
    (3, "3"),
    (3.5, "3+"),
    (3.75, "4-"),
    (4, "4"),
    (4.5, "4+"),
    (4.75, "5-"),
    (5, "5"),
    (5.5, "5+"),
    (5.75, "6-"),
    (6, "6")
)


class Student(models.Model):
    first_name = models.CharField(max_length=64, verbose_name='Imię')
    last_name = models.CharField(max_length=64, verbose_name='Nazwisko')
    school_class = models.IntegerField(choices=SCHOOL_CLASS, verbose_name='Klasa')
    email = models.EmailField(verbose_name='Email', blank=True)
    suspended = models.BooleanField(default=True, verbose_name='Aktywny')
    add_date = models.DateField(auto_now_add=True)
    active = models.BooleanField(default=True, verbose_name='Aktywny')


    class Meta:
        verbose_name = 'Student'
        verbose_name_plural = 'Studenci'

    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)


class Teacher(models.Model):
    first_name = models.CharField(max_length=64, verbose_name='Imię')
    last_name = models.CharField(max_length=64, verbose_name='Nazwisko')
    email = models.EmailField(verbose_name='Email', blank=True)
    suspended = models.BooleanField(default=True, verbose_name='Aktywny')
    add_date = models.DateField(auto_now_add=True)
    active = models.BooleanField(default=True, verbose_name='Aktywny')
    #rozbudowa użytkownika przez nadpisanie modelu

    class Meta:
        verbose_name = 'Nauczyciel'
        verbose_name_plural = 'Nauczyciele'

    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)


class SchoolSubject(models.Model):
    name = models.CharField(max_length=64, verbose_name='Przedmiot')
    # relationships: teacher
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, related_name='schoolsubject')

    class Meta:
        verbose_name = 'Przedmiot'
        verbose_name_plural = 'Przedmioty'

    def __str__(self):
        return self.name


class StudentGrades(models.Model):
    grade = models.FloatField(choices=GRADES)
    avg = models.FloatField(default=0)
    evaluation = models.TextField(null=True, default='NT')
    # relationships:
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='studentGrades')
    school_subject = models.ForeignKey(SchoolSubject, on_delete=models.CASCADE, related_name='studentGrades')

class FinalGrades(models.Model):
    avg1 = models.FloatField(default=0)
    avg2 = models.FloatField(default=0)
    half = models.FloatField(choices=GRADES, blank=True, null=True, default=0)
    final = models.FloatField(choices=GRADES, blank=True, null=True, default=0)
    # relationships:
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='finalGrades')
    school_subject = models.ForeignKey(SchoolSubject, on_delete=models.CASCADE, related_name='finalGrades')


class PresenceList(models.Model):
    day = models.DateField()
    present = models.NullBooleanField()
    # relationships:
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    school_subject = models.ForeignKey(SchoolSubject, on_delete=models.CASCADE, null=True)


class UnpreparedList(models.Model):
    unprep_one_used = models.BooleanField(default=False)
    unprep_two_used = models.BooleanField(default=False)
    # relationships:
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    school_subject = models.ForeignKey(SchoolSubject, on_delete=models.CASCADE)


''' ------------------- LIBRARY SECTION ------------------- '''

GENRES = (
    (1, 'podręczniki'),
    (2, 'prace naukowe'),
    (3, 'magazyny naukowe'),
    (4, 'ćwiczenia'),
    (5, 'vademecum'),
)


class Author(models.Model):
    first_name = models.CharField(max_length=256, verbose_name='Imie', null=True)
    last_name = models.CharField(max_length=256, verbose_name='Nazwisko', null=True)
    #books2

    class Meta:
        verbose_name = 'Autor'
        verbose_name_plural = 'Autorzy'

    @property
    def name(self):
        return '{} {}'.format(self.first_name, self.last_name)

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=256, verbose_name='Tytul', null=True)
    gender = models.IntegerField(choices=GENRES, verbose_name='Gatunek', null=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    is_borrowed = models.NullBooleanField(default=False, verbose_name='Wypożyczona?')
    date_added = models.DateField(auto_now_add=True)
    tags = models.ManyToManyField('Tag', related_name='books')  # 'Tag' bo klasa tag jest nizej
    authors = models.ManyToManyField(Author, related_name='books2')

    class Meta:
        verbose_name = 'Książka'
        verbose_name_plural = 'Książki'

    def name2(self):
        return '{}'.format(self.title)

    def __str__(self):
        return self.name2


class Tag(models.Model):
    tag_name = models.CharField(null=True, max_length=256, verbose_name='Tag')
    # books

    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tagi'

    def __str__(self):
        return self.tag_name

    def books_string(self):
        titles = [book.title for book in self.books.all()]
        return ', '.join(titles)


''' Auditorium Section '''

PROJECTOR_STATUS = (
    (1, 'projektor'),
    (2, 'brak projektora')
)


class Auditorium(models.Model):

    name = models.CharField(max_length=64)
    capacity = models.IntegerField(null=True)
    description = models.TextField(null=True)
    projector = models.IntegerField(choices=PROJECTOR_STATUS, null=True)

    class Meta:
        verbose_name = 'Aula'
        verbose_name_plural = 'Aule'

    def __str__(self):
        return self.name


class Booking(models.Model):
    date = models.DateField(null=True)
    auditorium = models.ForeignKey(Auditorium, null=True, related_name='room', on_delete=models.CASCADE)
    teacher = models.ForeignKey(Teacher, null=True, related_name='teacher', on_delete=models.CASCADE)

    def __str__(self):
        return str(self.date)

smpapp/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import (
    GRADES, Student, UnpreparedList, Book, Booking, FinalGrades
)


''' Teacher Section '''


class StudentSearchForm(forms.Form):
    name = forms.CharField(label='Nazwisko ucznia')


class StudentGradesForm(forms.Form):
    grade = forms.ChoiceField(label='Ocena', choices=GRADES)
    evaluation = forms.CharField(max_length=1024)


class FinalGradesForm(forms.ModelForm):
    class Meta:
        model = FinalGrades
        fields = ['half', 'final']


class PresenceListForm(forms.Form):

    student = forms.CharField(label='Student', widget=forms.HiddenInput())
    day = forms.DateField(label='Data', widget=forms.HiddenInput())
    present = forms.NullBooleanField(label='Obecny? ')


class UnpreparedListForm(forms.ModelForm):
    class Meta:
        model = UnpreparedList
        fields = '__all__'


''' Auth Section '''


class LoginForm(forms.Form):
    login = forms.CharField(label='Login')
    password = forms.CharField(label='Haslo', widget=forms.PasswordInput)


class ChangePassForm(forms.Form):
    old_pass = forms.CharField(widget=forms.PasswordInput())
    new_pass = forms.CharField(widget=forms.PasswordInput())
    new_pass_2 = forms.CharField(widget=forms.PasswordInput())


''' Library Section '''


class NewBookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'gender', 'is_borrowed', 'tags', 'authors', 'authors' ]




''' Auditorium  Section '''

class NewBookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = '__all__'

smpapp/templates/class_presence.html
{% extends 'panel_1.html' %}



{% block content %}

<h2>Lista obecności</h2>
<p>Student: <b>{{ student.first_name }} {{ student.last_name }}</b></p>
<p>Dzień: <b>{{ date }}</b></p>

    <form method="POST">

        {% csrf_token %}
        {{ form }}

        <input type="submit">
    </form>

{% endblock %}

smpapp/templates/library.html
{% extends 'panel_1.html' %}

{% block content %}
<h2>Szkolna biblioteka</h2>
<a href="{% url 'book_create' %}">Dodaj</a>
<br>
<table class="table table-striped">
         <thead>
             <tr>
                 <th>Tytuł</th>
                 <th>Autor</th>
                 <th>Gatunet</th>
                 <th></th>
              </tr>
         </thead>
         <tbody>
         {% for book in books %}
             <tr>
                 <td>{{ book.title }}</td>
                 <td>{{ book.author }}</a></td>
                 <td>{{ book.gender }}</td>
                 <td><a href="/book/{{ book.id }}/{{ subject.id }}/{{ s.id }}/unpr">Więcej</a></td>
             </tr>
        {% endfor %}
        </tbody>
     </table>
   </div>

{% endblock %}

smpapp/templates/login-2.html
{% extends 'starter.html' %}

{% block content %}
    <form method="POST">

        {% csrf_token %}
        {{ form }}

        <input type="submit">
    </form>

{% endblock %}

smpapp/templates/login.html
<!DOCTYPE html>
<html>
<head>
  {% load staticfiles %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="{% static 'auth/login.css' %}">
</head>
<body>

 <form method="POST">
   <div class="container">
   <h2>Login Form</h2>
     <div class="imgcontainer">
        <img src="{% static 'LP/img/logo2.png' %}" alt="Avatar" class="avatar">
     </div>

        {% csrf_token %}
        {{ form }}

     <button type="submit">Login</button>
   </div>
   <span class="psw">Forgot <a href="#">password?</a></span>
 </form>

</body>
</html>

smpapp/templates/panel.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load staticfiles %}
  <title>Stud.Man.Pro</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="{% static 'auth/panel.css' %}">
</head>
<body>

<nav class="navbar navbar-inverse visible-xs">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">
        <img src="{% static 'LP/img/logo2.png' %}" alt="Avatar" class="avatar">
      </a>

    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">

        <li class="active"><a href="#">Klasa-mobi</a></li>
          {% for c in cp_class %}
            <li><a href="/teacher/{{ c.0 }}">{{ c.1 }}</a></li>
          {% endfor %}

        <li><p><a href="tryit.asp-filename=trybs_navbar_right&stacked=h.html#"><span class="glyphicon glyphicon-user"></span> {{ request.user.username }}</a></p></li>

        {% if request.user.is_authenticated %}
            <p><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span> Wyloguj</a></p>
        {% else %}
            <p><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span>Zaloguj</a></p>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-2 sidenav hidden-xs">
      <br>
      <img src="{% static 'LP/img/logo2.png' %}" alt="Avatar" class="avatar">
      <br>
      <hr>

          {% for c in cp_class %}
          <!-- Default dropright button -->
            <div class="btn-group dropright">
              <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"
                      aria-haspopup="true" aria-expanded="false">{{ c.1 }}
              </button>
              <div class="dropdown-menu">
                <!-- Dropdown menu links -->
                  {% for s in cp_subjects %}
                  <li><a class="dropdown-item" href="/teacher/{{ c.0 }}/{{s.pk}}">{{ s.name }}</a></li>
                  {% endfor %}
              </div>
            </div>
        <br>
          {% endfor %}

        <hr>

        <p><a href="tryit.asp-filename=trybs_navbar_right&stacked=h.html#">
            <span class="glyphicon glyphicon-user"></span> {{ request.user.username }}</a>
            </p>


        {% if request.user.is_authenticated %}
            <p><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span> Wyloguj</a></p>
        {% else %}
            <p><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span>Zaloguj</a></p>
        {% endif %}
      <br>
    </div>
    <br>


      <div class="col-sm-10">
          <div class="well">
                {% block teacher_diary %}
                {% endblock teacher_diary %}
          </div>


          <div class="well">

            {% block final_grades %}
            {% endblock final_grades %}

          </div>


          <div class="well">

            {% block absence_list %}
            {% endblock absence_list %}

          </div>


          <div class="well">

            {% block used_unprepared %}
            {% endblock used_unprepared %}

        </div>

      </div>
    </div>
  </div>
</div>

</body>
</html>

smpapp/templates/panel_1.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load staticfiles %}
  <title>Stud.Man.Pro</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="{% static 'auth/panel.css' %}">
</head>
<body>

<nav class="navbar navbar-inverse visible-xs">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">
        <img src="{% static 'LP/img/logo2.png' %}" alt="Avatar" class="avatar">
      </a>

    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">

        <li class="active"><a href="#">Klasa-mobi</a></li>
          {% for c in cp_class %}
            <li><a href="/teacher/{{ c.0 }}">{{ c.1 }}</a></li>
          {% endfor %}

        <li class="active"><a href="{% url 'library' %}">Bibliotek</a></li>

        <li><p><a href="tryit.asp-filename=trybs_navbar_right&stacked=h.html#"><span class="glyphicon glyphicon-user"></span> {{ request.user.username }}</a></p></li>

        {% if request.user.is_authenticated %}
            <p><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span> Wyloguj</a></p>
        {% else %}
            <p><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span>Zaloguj</a></p>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-2 sidenav hidden-xs">
      <br>
      <img src="{% static 'LP/img/logo2.png' %}" alt="Avatar" class="avatar">
      <br>
      <hr>

          {% for c in cp_class %}
          <!-- Default dropright button -->
            <div class="btn-group dropright">
              <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown"
                      aria-haspopup="true" aria-expanded="false">{{ c.1 }}
              </button>
              <div class="dropdown-menu">
                <!-- Dropdown menu links -->
                  {% for s in cp_subjects %}
                  <li><a class="dropdown-item" href="/teacher/{{ c.0 }}/{{s.pk}}">{{ s.name }}</a></li>
                  {% endfor %}
              </div>
            </div>
        <br>
          {% endfor %}

        <hr>

        <p><a href="/teacher/{{ request.user.id }}">
            <span class="glyphicon glyphicon-user"></span> {{ request.user.username }}</a>
            </p>


        {% if request.user.is_authenticated %}
            <p><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span> Wyloguj</a></p>
        {% else %}
            <p><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span>Zaloguj</a></p>
        {% endif %}
      <br>
    </div>
    <br>



      <div class="col-sm-10">
          <div class="well">
                {% block content %}
                {% endblock content %}
          </div>
      </div>



    </div>
  </div>
</div>

</body>
</html>

smpapp/templates/signup-2.html
{% extends 'starter.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

smpapp/templates/starter.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  </head>
  <body>
    <section>
        {% block content %}
        {% endblock content %}
    </section>
    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  </body>
</html>

smpapp/templates/student_full.html
{% extends 'panel_2.html' %}

      {% block profil %}
      <div class="title">
                <div class="title-icon">
                    <i class="fa fa-gears"></i>
                </div>
                <div class="title-text">
                    <h2 class="title-heading">Profil</h2>
                </div>
            </div>
      <div class="profil-center">
            <p>Imię: {{ student.first_name }}</p>
            <p>Nazwisko: {{ student.last_name }}</p>
            <p>Klasa: {{ student.get_school_class_display }}</p>
      </div>
      {% endblock profil %}

      {% block diary %}
      <div class="title">
                <div class="title-icon">
                    <i class="fa fa-gears"></i>
                </div>
                <div class="title-text">
                    <h2 class="title-heading">Dzienniczek</h2>
                </div>
            </div>
      <div class="diary-center">
      <table class="table table-striped">
         <thead>
             <tr>
                  <th>Id</th>
                  <th>Przedmiot</th>
                   <th>Oceny</th>
                    <th>Uwagi</th>
              </tr>
         </thead>
         <tbody>
         {% for sub in cp_subjects %}
             <tr>
                 <td>{{ sub.id }}</td>
                 <td>{{ sub }}</td>
                 <td>
                     <ul>
                         {% for g in grades %}
                             {% if g.student_id == sub.id %}
                                <li>{{ g.grade }}</li>
                             {% endif %}
                         {% endfor %}
                     </ul>

                 </td>
                                  <td>
                     <ul>
                         {% for g in grades %}
                             {% if g.student_id == sub.id %}
                                <li>{{ g.evaluation }}</li>
                             {% endif %}
                         {% endfor %}
                     </ul>

                 </td>
             </tr>
        {% endfor %}
        </tbody>
      </table>
      </div>
      {% endblock diary %}

      {% block unprepared %}
      <div class="title">
                <div class="title-icon">
                    <i class="fa fa-gears"></i>
                </div>
                <div class="title-text">
                    <h2 class="title-heading">Nieprzygotowania</h2>
                </div>
            </div>
      <div class="unprepared-center">
      <table class="table table-striped">
          <thead>
              <tr>
                  <th>Przedmiot</th>
                  <th>Nieprzydotowanie 1</th>
                  <th>Nieprzydotowanie 2</th>
              </tr>
              {% for sub in cp_subjects %}
              <tr>
                 <td>{{ sub }}</td>
                 <td>
                     {% for unp in unprepared_list %}
                         {% if unp.school_subject_id == sub.id %}
                            {{ unp.unprep_one_used }}
                         {% endif %}
                     {% endfor %}
                 </td>
                 <td>
                     {% for unp in unprepared_list %}
                         {% if unp.school_subject_id == sub.id %}
                            {{ unp.unprep_two_used }}
                         {% endif %}
                     {% endfor %}
                 </td>
             </tr>
        {% endfor %}
        </tbody>
      </table>
      </div>
      {% endblock unprepared %}

smpapp/templates/student_search.html
{% extends 'panel_1.html' %}

{% block content %}
    <h2>Wyszukaj studenta</h2>
    <form method="POST">

        {% csrf_token %}
        {{ form }}

        <input type="submit">
    </form>

        {% for s in students %}
            <hr>
            <p>id: <strong>{{ s.id }}</strong></p>
            <p>Imię: <strong>{{ s.first_name }}</strong></p>
            <p>Nazwisko: <strong>{{ s.last_name }}</strong></p>
            <p>Klasa: <strong>{{ s.get_school_class_display }}</strong></p>
            <p>Aktywny: <strong>{{ s.active }}</strong></p>
            <p><a href="/student/{{ s.id }}">Więcej danych</a></p>

        {% empty %}
            <p>Wyszukaj ponownia</p>
        {% endfor%}

{% endblock %}

smpapp/templates/teacher_grades_final.html
{% extends 'panel_1.html' %}

{% block content %}

    <p>Student: <b>{{ stud.first_name }} {{ stud.last_name }}</b></p>
    <p>Klasa: <b>{{ stud.get_school_class_display }}</b></p>
    <p>Oceny: {% for g in grades %}{{ g.get_grade_display }}, {% endfor %}</p>
    <p>Średnia: {{ avg }}</p>

<br>
    <form method="post">

            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit">
    </form>

{% endblock %}

smpapp/templates/teacher_profil.html
{% extends 'panel_1.html' %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>
{% endblock %}

smpapp/templates/unprepared_form.html
{% extends 'panel_1.html' %}

{% block content %}
    <form method="POST">

        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit">
    </form>

{% endblock %}